version: '3'
services:
  app:
    build:
      context: .
      dockerfile: src/app/Dockerfile
    container_name: portfolio
    ports:
      - "80:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
